# yaml-language-server: $schema=https://raw.githubusercontent.com/shyim/tanjun/refs/heads/main/schema.json
name: shopware-nightly
image: ghcr.io/shopwarelabs/shopware-nightly
keep_versions: 5
build:
    build_pack:
        type: shopware
        settings:
          profiler: tideways
          ini:
            tideways.sample_rate: '10'
            opcache.preload: '/app/var/cache/opcache-preload.php'
    dockerfile: Dockerfile
server:
    address: nightly.sw-bench.de
    username: root
    port: 22
proxy:
    host: nightly.sw-bench.de
    healthcheck:
        interval: 1
        timeout: 5
        path: /
    response_timeout: 30
    ssl: true
app:
  env:
    APP_URL:
      expr: '"https://" + config.Proxy.Host'
    APP_ENV:
      value: prod
    SHOPWARE_HTTP_CACHE_ENABLED:
      value: "1"
    COMPOSER_PLUGIN_LOADER:
      value: "1"
    DATABASE_PERSISTENT_CONNECTION:
      value: "1"
    SQL_SET_DEFAULT_SESSION_VARIABLES:
      value: "0"
    ENABLE_SERVICES:
      value: "0"
    DATABASE_URL:
      expr: 'service.database.url'
    TIDEWAYS_CONNECTION:
      expr: 'service.tideways.url'
  initial_secrets:
    APP_SECRET:
      expr: 'randomString(32)'
  secrets:
    from_stored:
      TIDEWAYS_APIKEY:
  mounts:
    jwt:
      path: config/jwt
    files:
      path: files
    bundles:
      path: public/bundles
    theme:
      path: public/theme
    media:
      path: public/media
    thumbnail:
      path: public/thumbnail
    sitemap:
      path: public/sitemap
  workers:
    worker:
      command: 'php bin/console messenger:consume async --time-limit=3600'
  cronjobs:
    - name: scheduled-task
      schedule: '@every 5m'
      command: 'php bin/console scheduled-task:run --no-wait'
  hooks:
    deploy: |
      ./vendor/bin/shopware-deployment-helper run --skip-theme-compile
    post_deploy: |
      ./bin/console theme:compile --active-only

services:
  database:
    type: mysql:8.0
    settings:
      sql_mode: 'error_for_division_by_zero'
  cache:
    type: valkey:8.0
  tideways:
    type: tideways:latest
