name: Deploy
on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:
concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Setup Tanjun
        uses: shyim/setup-tanjun@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-server-host: nightly.sw-bench.de

      - name: Deploy
        run: tanjun deploy --verbose
