name: Deploy
on:
  push:
    branches:
      - main

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install tanjun
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: shyim/tanjun

      - name: Add Host Key
        run: ssh-keyscan nightly.sw-bench.de >> ~/.ssh/known_hosts

      - name: Deploy
        run: tanjun deploy --verbose
